name: Build and Deploy

on:
  push:
      branches:
        - main

defaults:
  run:
    shell: bash

jobs:
  install_build_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Get Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.x

      - name: Install packages
        run: |
          yarn install --frozen-lockfile

      - name: Build Site
        run: |
          yarn build
        env:
          CI: false
          PUBLIC_URL: https://genesysnitrkl.github.io/genesys/

      - name: copy nojekyll to build
        run: |
          touch .nojekyll
          mv .nojekyll build/.nojekyll
        
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.7
        with:
          branch: gh-pages
          folder: build